### PR TITLE
Replaced the cancel button from the detail dialog

### PR DESCRIPTION
**Pull request by shiraji**
As we discuss 9/15, I will try to replace cancel button from DetailDialog.

### CODE REVIEW

**Comment by shiraji** [comment]
According to documentation [here](https://confluence.jetbrains.com/display/IDEADEV/IntelliJ+IDEA+DialogWrapper)

> To customize the buttons displayed in the dialog (replacing the standard OK/Cancel/Help set of buttons), you can override either the createActions() or createLeftActions() methods. Both of these methods return an array of Swing Action objects. If the button that you're adding closes the dialog, you can use DialogWrapperExitAction as the base class for your action.

So, I created OK button with `OK_EXIT_CODE` using DialogWrapperExitAction. This really replaced CANCEL button. I can change CLOSE button with some type of exit code like `CLOSE_EXIT_CODE` which is the same value with `CANCEL_EXIT_CODE`. What do you think, @androhi ?

**Comment by androhi** [comment]
Thank you for your PR!!!
Sorry, give me a little time...

**Comment by shiraji** [comment]
Off course! Thanks for taking your time.

**Comment by androhi** [comment]
Well, I think it is good! Perfect!
I will merge this pull-request later.

**Comment by shiraji** [comment]
I rebased this branch for merge. Thanks for confirming this pull request!

**Comment by androhi** [comment]
LGTM!

**Comment by shiraji** [comment]
tiqav

**Pull request merged**
